### EJERCICIOS PYTHON

In [2]:
import numpy as np

##### 1. Write a Python program to convert a list of numeric value into a one-dimensional Numpy array. Expected Output:
Original List: [12.23,13.32,100,36.32]
One-dimensional numpy array: [12.23 13.32 100. 36.32 ]

In [15]:
lista =[12.23,13.32,100,36.32]

In [19]:
numpy_array = np.array(lista)
print(numpy_array)

[  12.23   13.32  100.     36.32]


##### 2. Write a Python program to create a null vector of size 10 and update sixth value to 11

In [10]:
v = np.zeros(10)
v[5] = 11
v

array([  0.,   0.,   0.,   0.,   0.,  11.,   0.,   0.,   0.,   0.])

##### 3. Write a Python program to create a array with values ranging from 12 to 38.

In [7]:
v = np.arange(12,39)
v

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

##### 4. Write a Python program to reverse an array (first element becomes last).

In [12]:
v = np.arange(1,10)
v

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
v[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

##### 5. WriteaPythonprogramtocreatea2darraywith1ontheborderand0inside.Expected Output: Original array: [[ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 1. 1. 1. 1.]] 

In [4]:
D = np.matrix([[1,1,1,1,1], [1,0,0,0,1], [1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]])
D

matrix([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]])

##### 6. Write a Python program to add a border (filled with 0’s) around an existing array.

In [14]:
V = np.ones((5,5))
print( ' Arreglo original:')
print(V)
Z = np.pad(V, pad_width=1, mode='constant', constant_values=0)
print('Arreglo con borde de ceros : ')
print(Z)

 Arreglo original:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
Arreglo con borde de ceros : 
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


##### 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern Checkerboard pattern: [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]] hint: Explore the use of x[a :: b,:: c]= d,x[:: e,f :: g]= h, where the letters are integer numbers.

In [3]:
Z = np.ones((8,8),dtype=int)
Z[1::2,::2] = 0
Z[::2,1::2] = 0
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


##### 8. Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. Sample Array [0, 12, 45.21 ,34, 99.91] Expected Output: Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91] ValuesinCentigradedegrees:[-17.77777778-11.111111117.338888891.1111111137.72777778]. Usefunctionsandlistcomprehensionreadthelinkhttps://www.pythonforbeginners. com/lists/list-comprehensions-in-python/, to additional information about of list comprehension in python

In [20]:
lista = [0, 12, 45.21 ,34, 99.91] 
lista

[0, 12, 45.21, 34, 99.91]

In [22]:
[i for i in lista]
gradosc=[((i-32)*(5/9)) for i in lista]
print(gradosc)

[-17.77777777777778, -11.11111111111111, 7.3388888888888895, 1.1111111111111112, 37.727777777777774]


##### 9. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Expected Output: Array1: [ 0 10 20 40 60 80] Array2: [10, 30, 40, 50, 70, 90] Set difference between two arrays: [ 0 20 60 80] Hint:explore the use of function np.setdiff1d.

In [23]:
Array1=[0,10,20,40,60,80]
Array2=[10,30,40,50,70,90]

In [25]:
dif =np.setdiff1d(Array1,Array2)
dif

array([ 0, 20, 60, 80])

##### 10. Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s elsewhere.

In [26]:
diagonal=np.diag([4,5,6,8])
print(diagonal)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
