In [1]:
### Sobre lo que espero en la clase, creo que es una materia fundamental, pero por mismas razones, no será una materia sencilla, ni muchos menos de poco trabajo. Espero que mas que difícil sea de trabajo ya que la base del curso es prgramación y a menos de que lo que se pida sean códigos de un exagerdo nivel de complejidad, no veo por que la materia sería "difícil" con tntes de imposible, sino más bien una materia de trabajo, lógica y prueba y error.

In [1]:
print("Sobre lo que espero en la clase, creo que es una materia fundamental, pero por mismas razones, no será una materia sencilla, ni muchos menos de poco trabajo. Espero que mas que difícil sea de trabajo ya que la base del curso es prgramación y a menos de que lo que se pida sean códigos de un exagerdo nivel de complejidad, no veo por que la materia sería difícil con tntes de imposible, sino más bien una materia de trabajo, lógica y prueba y error.")

Sobre lo que espero en la clase, creo que es una materia fundamental, pero por mismas razones, no será una materia sencilla, ni muchos menos de poco trabajo. Espero que mas que difícil sea de trabajo ya que la base del curso es prgramación y a menos de que lo que se pida sean códigos de un exagerdo nivel de complejidad, no veo por que la materia sería difícil con tntes de imposible, sino más bien una materia de trabajo, lógica y prueba y error.


In [4]:
print("Sobre lo que espero en la clase, creo que es una materia fundamental, pero por mismas razones, no será una materia sencilla, ni muchos menos de poco trabajo. Espero que mas que difícil sea de trabajo ya que la base del curso es prgramación y a menos de que lo que se pida sean códigos de un exagerdo nivel de complejidad, no veo por que la materia sería difícil con tntes de imposible, sino más bien una materia de trabajo, lógica y prueba y error.")

Sobre lo que espero en la clase, creo que es una materia fundamental, pero por mismas razones, no será una materia sencilla, ni muchos menos de poco trabajo. Espero que mas que difícil sea de trabajo ya que la base del curso es prgramación y a menos de que lo que se pida sean códigos de un exagerdo nivel de complejidad, no veo por que la materia sería difícil con tntes de imposible, sino más bien una materia de trabajo, lógica y prueba y error.


In [5]:
print("problema 1 Jm_ochoa")
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional numpy array: ",a)

problema 1 Jm_ochoa
('Original List:', [12.23, 13.32, 100, 36.32])
('One-dimensional numpy array: ', array([  12.23,   13.32,  100.  ,   36.32]))


In [6]:
print("problma 2 jm_ochoa")
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

problma 2 jm_ochoa
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
Update sixth value to 11
[  0.   0.   0.   0.   0.   0.  11.   0.   0.   0.]


In [7]:
print("problema 3 jm_ochoa")
x = np.arange(12, 38)
print(x)

problema 3 jm_ochoa
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37]


In [10]:
print("problema 4 jm_ochoa")
original = np.arange(1, 11)
print("Original")
print(original)
print("Invertido")
inv = original[::-1]
print(inv)

problema 4 jm_ochoa
Original
[ 1  2  3  4  5  6  7  8  9 10]
Invertido
[10  9  8  7  6  5  4  3  2  1]


In [11]:
print("problema 5 jm_ochoa")
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

problema 5 jm_ochoa
Original array:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
1 on the border and 0 inside in the array
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [13]:
print("problema 6 jm_ochoa")
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

problema 6 jm_ochoa
Original array:
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
0 on the border and 1 inside in the array
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


In [14]:
print("problema 7 jm_ochoa")
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

problema 7 jm_ochoa
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
print("problema 8 jm_ochoa")
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9) 
print("por discrepacians en el modod de conversón los resultados resultaon más aproximados que exactos.")

problema 8 jm_ochoa
Values in Fahrenheit degrees:
[  0.    12.    45.21  34.    99.91]
Values in  Centigrade degrees:
[-17.         -10.33333333   8.11666667   1.88888889  38.50555556]
por discrepacians en el modod de conversón los resultados resultaon más aproximados que exactos


In [20]:
print("problema 9 jm_ochoa")
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

problema 9 jm_ochoa
('Array1: ', array([ 0, 10, 20, 40, 60, 80]))
('Array2: ', [10, 30, 40, 50, 70])
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [21]:
print("problema 10 jm_ochoa")
x =  np.diagflat([4, 5, 6, 8])
print(x)

problema 10 jm_ochoa
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
